export const FAILED_REGISTER = "FAILED_REGISTER";
export const FAILED_LOAD_USER = "FAILED_LOAD_USER";
export const FAILED_LOGIN = "FAILED_LOGIN";

export const LOADING_REGISTER = "LOADING_REGISTER";
export const LOADING_LOAD_USER = "LOADING_LOAD_USER";
export const LOADING_LOGIN = "LOADING_LOGIN";


export const REGISTER_SUCESS= "REGISTER_SUCESS";
export const LOGIN_SUCESS= "LOGIN_SUCESS";
export const LOAD_USER_SUCESS= "LOAD_USER_SUCESS";

export const LOG_OUT= "LOG_OUT"

export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const GET_USERS_FAILED="GET_USERS_FAILED"
export const GET_USERS_LOADING="GET_USERS_LOADING"


export const UPDATE_USER_LOADING="UPDATE_USER_LOADING"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILED="UPDATE_USER_FAILED"

export const GET_CATEGORY_SUCESS="GET_CATEGORY_SUCESS"
export const GET_CATEGORY_LOADING="GET_CATEGORY_LOADING"
export const GET_CATEGORY_FAILED="GET_CATEGORY_FAILED"

export const GET_ALL_CATEGORIES_SUCESS = "GET_ALL_CATEGORIES_SUCESS"
export const GET_ALL_CATEGORIES_LOADING = "GET_ALL_CATEGORIES_LOADING"
export const GET_ALL_CATEGORIES_FAILED = "GET_ALL_CATEGORIES_FAILED"

export const ADD_CATEGORY_SUCESS="ADD_CATEGORY_SUCESS"
export const ADD_CATEGORY_LOADING="ADD_CATEGORY_LOADING"
export const ADD_CATEGORY_FAILED="ADD_CATEGORY_FAILED"

export const DELETE_CATEGORY_SUCESS = "DELETE_CATEGORY_SUCESS"
export const DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING"
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED"

export const UPDATE_CATEGORY_SUCESS="UPDATE_INGREDIENT_SUCCESS"
export const UPDATE_CATEGORY_FAILED="UPDATE_INGREDIENT_FAILED"
export const UPDATE_CATEGORY_LOADING="UPDATE_INGREDIENT_LOADING"

export const GET_INGREDIENT_SUCESS = "GET_INGREDIENT_SUCESS"
export const GET_INGREDIENT_LOADING = "GET_INGREDIENT_LOADING"
export const GET_INGREDIENT_FAILED = "GET_INGREDIENT_FAILED"



export const ADD_INGREDIENT_SUCESS = "ADD_INGREDIENT_SUCESS"
export const ADD_INGREDIENT_LOADING = "ADD_INGREDIENT_LOADING"
export const ADD_INGREDIENT_FAILED = "ADD_INGREDIENT_FAILED"


export const DELETE_INGREDIENT_SUCESS = "DELETE_INGREDIENT_SUCESS"
export const DELETE_INGREDIENT_LOADING = "DELETE_INGREDIENT_LOADING"
export const DELETE_INGREDIENT_FAILED = "DELETE_INGREDIENT_FAILED"

export const GET_ALL_INGREDIENT_SUCESS = "GET_ALL_INGREDIENT_SUCESS"
export const GET_ALL_INGREDIENT_LOADING = "GET_ALL_INGREDIENT_LOADING"
export const GET_ALL_INGREDIENT_FAILED = "GET_ALL_INGREDIENT_FAILED"

export const UPDATE_INGREDIENT_SUCCESS="UPDATE_INGREDIENT_SUCCESS"
export const UPDATE_INGREDIENT_FAILED="UPDATE_INGREDIENT_FAILED"
export const UPDATE_INGREDIENT_LOADING="UPDATE_INGREDIENT_LOADING"


export const ADD_TO_BOL_SUCESS= "ADD_BOL_SUCESS"
export const DELETE_FROM_BOL= "DELETE_FROM_BOL"
export const RESET_BOL="RESET_BOL"


export const ADD_COMMANDE="ADD_COMMANDE"
export const UPDATE_COMMANDE="UPDATE_COMMANDE"
export const GET_COMMANDE="GET_COMMANDE"
export const DELETE_COMMANDE="DELETE_COMMANDE"
export const RESET_COMMANDE="RESET_COMMANDE"

export const LIVRAISON="LIVRAISON"
export const TOTAL="TOTAL"
export const LOCALISATION="LOCALISATION"


export const GET_SHIPPING_PRICE_SUCESS="GET_SHIPPING_PRICE_SUCESS"
export const GET_SHIPPING_PRICE_FAILED="GET_SHIPPING_PRICE_FAILED"


export const UPDATE_SHIPPING_PRICE="UPDATE_SHIPPING_PRICE"
export const ADD_SHIPPING_PRICE="ADD_SHIPPING_PRICE"

export const ADD_DETAILS="ADD_DETAILS"

export const ADD_ORDER_SUCESS="ADD_ORDER_SUCESS"
export const ADD_ORDER_LOADING="ADD_ORDER_LOADING"
export const ADD_ORDER_FAILED ="ADD_ORDER_FAILED"

export const GET_ORDERS_SUCESS="GET_ORDERS_SUCESS"
export const GET_ORDERS_FAILED="GET_ORDERS_FAILED"
export const GET_ORDERS_LOADING="GET_ORDERS_LOADING"

export const UPDATE_ORDER_SUCCESS="UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAILED="UPDATE_ORDER_FAILED"
export const UPDATE_ORDER_LOADING="UPDATE_ORDER_LOADING"

export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILED="DELETE_ORDER_FAILED"
export const DELETE_ORDER_LOADING="DELETE_ORDER_LOADING"


export const GET_ORDER_SUCCESS="GET_ORDER_SUCCESS"
export const GET_ORDER_FAILED="GET_ORDER_FAILED"
export const GET_ORDER_LOADING="GET_ORDER_LOADING"